-- base46 colorscheme, generated by `omarchy theme set` and loaded by nvim's colorscheme.lua
local base46 = require("base46")
base46.theme_tables.omarchy = {
  type = "{{ mode }}",
  base_30 = {
    white = "{{ bright_foreground }}",
    darker_black = "{{ mix background darker_background 50% }}",
    black = "{{ background }}",
    black2 = "{{ mix background foreground 6% }}",
    one_bg = "{{ mix background foreground 10% }}",
    one_bg2 = "{{ mix background foreground 16% }}",
    one_bg3 = "{{ mix background foreground 22% }}",
    grey = "{{ mix background foreground 28% }}",
    grey_fg = "{{ mix background foreground 34% }}",
    grey_fg2 = "{{ mix background foreground 40% }}",
    light_grey = "{{ mix background foreground 48% }}",
    red = "{{ red }}",
    baby_pink = "{{ bright_red }}",
    pink = "{{ magenta }}",
    line = "{{ mix background foreground 14% }}",
    green = "{{ green }}",
    vibrant_green = "{{ bright_green }}",
    nord_blue = "{{ bright_blue }}",
    blue = "{{ blue }}",
    yellow = "{{ yellow }}",
    sun = "{{ bright_yellow }}",
    purple = "{{ magenta }}",
    dark_purple = "{{ bright_magenta }}",
    teal = "{{ cyan }}",
    orange = "{{ orange }}",
    cyan = "{{ bright_cyan }}",
    statusline_bg = "{{ mix background foreground 4% }}",
    lightbg = "{{ mix background foreground 12% }}",
    pmenu_bg = "{{ accent }}",
    folder_bg = "{{ accent }}",
  },
  base_16 = {
    base00 = "{{ background }}",
    base01 = "{{ mix background foreground 8% }}",
    base02 = "{{ selection }}",
    base03 = "{{ muted }}",
    base04 = "{{ dark_foreground }}",
    base05 = "{{ foreground }}",
    base06 = "{{ light_foreground }}",
    base07 = "{{ bright_foreground }}",
    base08 = "{{ red }}",
    base09 = "{{ orange }}",
    base0A = "{{ yellow }}",
    base0B = "{{ green }}",
    base0C = "{{ cyan }}",
    base0D = "{{ blue }}",
    base0E = "{{ magenta }}",
    base0F = "{{ brown }}",
  },
}
base46.load("omarchy")

-- Hot reload, once per nvim: `omarchy theme set` swaps in a new theme folder and then writes theme.name,
-- so watch that and re-run this file (the path stays the same, the contents are the new theme's)
if not _G._omarchy_theme_watcher then
  local this_file = debug.getinfo(1, "S").source:sub(2)
  _G._omarchy_theme_watcher = vim.uv.new_fs_event()
  _G._omarchy_theme_watcher:start(vim.fn.expand("~/.local/state/omarchy/current/theme.name"), {}, function()
    vim.schedule(function()
      dofile(this_file)
    end)
  end)
end
